service: product-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 768
functions:
  coupons:
    handler: index.handler
    events:
      - http:
          path: products
          method: get
      - http:
          path: products/{id}
          method: get
      - http:
          path: products
          method: post
      - http:
          path: products/{id}
          method: put
      - http:
          path: products/{id}
          method: delete
# # plugins:
#   - serverless-offline
