---
AWSTemplateFormatVersion: 2010-09-09

Description: API Gateway, Lambda, and Dynamo.

Resources:
  # Policy required for all lambda function roles.
  BaseLambdaExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Base permissions needed by all lambda functions.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - ec2:CreateNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
            Resource: "*"

  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

  # FIXME How to hook up custom domain?
  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${AWS::StackName}-MyApiGateway"
      Description: A description
      FailOnWarnings: true
      Body:
        openapi: 3.0.0
        info:
          description: >
            Finest apparel by Wu, Raulin & Co. Product service.


          version: "1.0.0-oas3"
          title: Wu, Raulin & Co. Outfitter Product Service
          termsOfService: "http://swagger.io/terms/"
          contact:
            email: lee.raulin@smoothstack.com
        tags:
          - name: products
            description: Everything about the world's finest apparel products by Wu, Raulin & Co.
        paths:
          /{proxy+}:
            x-amazon-apigateway-integration:
              uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProductLambda.Arn}/invocations"
              credentials: !GetAtt MyApiGatewayRole.Arn
              passthroughBehavior: when_no_match
              httpMethod: POST
              type: aws_proxy
          /products:
            get:
              tags:
                - products
              summary: Finds products in the store
              description: Multiple status values can be provided with comma separated strings
              operationId: readProducts
              parameters:
                - name: department
                  in: query
                  description: Department to filter by
                  required: false
                  schema:
                    type: string
                - name: category
                  in: query
                  description: Category to filter by
                  required: false
                  schema:
                    type: string
              responses:
                "200":
                  description: OK
                  content:
                    application/json:
                      schema:
                        type: array
                        items:
                          $ref: "#/components/schemas/Product"
                    application/xml:
                      schema:
                        type: array
                        items:
                          $ref: "#/components/schemas/Product"
                "400":
                  description: Invalid status value
            post:
              tags:
                - products
              summary: Creates a new product for the store
              operationId: createProduct
              parameters:
                - name: Authorization
                  in: header
                  required: true
                  schema:
                    type: string
              responses:
                "201":
                  description: Product created
                "405":
                  description: Invalid input
              security:
                - Bearer: []
              requestBody:
                $ref: "#/components/requestBodies/Product"
          "/products/{product_id}":
            get:
              tags:
                - products
              summary: Finds a product by ID
              description: Returns a single product
              operationId: readProductById
              parameters:
                - name: product_id
                  in: path
                  description: ID of products to return
                  required: true
                  schema:
                    type: integer
                    format: int64
              responses:
                "200":
                  description: OK
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Product"
                    application/xml:
                      schema:
                        $ref: "#/components/schemas/Product"
                "404":
                  description: Product not found
            put:
              tags:
                - products
              summary: Updates a product
              operationId: updateProduct
              parameters:
                - name: Authorization
                  in: header
                  required: true
                  schema:
                    type: string
                - name: product_id
                  in: path
                  description: ID of products that needs to be updated
                  required: true
                  schema:
                    type: integer
                    format: int64
              responses:
                "200":
                  description: OK
                "405":
                  description: Invalid input
              security:
                - Bearer: []
              requestBody:
                $ref: "#/components/requestBodies/Product"
            delete:
              tags:
                - products
              summary: Deletes a product
              operationId: deleteProduct
              parameters:
                - name: Authorization
                  in: header
                  required: true
                  schema:
                    type: string
                - name: product_id
                  in: path
                  description: product id to delete
                  required: true
                  schema:
                    type: integer
                    format: int64
              responses:
                "204":
                  description: Successfully deleted
                "404":
                  description: Product not found
              security:
                - Bearer: []
        externalDocs:
          description: Find out more about Swagger
          url: "http://swagger.io"
        servers:
          - url: "https://virtserver.swaggerhub.com/SmoothStack38/FashionStore/1.0.0"
          - url: "http://virtserver.swaggerhub.com/SmoothStack38/FashionStore/1.0.0"
        components:
          requestBodies:
            Product:
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Product"
                application/xml:
                  schema:
                    $ref: "#/components/schemas/Product"
              description: products object that needs to be added to the store
              required: true
          securitySchemes:
            Bearer:
              type: apiKey
              name: JWT
              in: header
          schemas:
            Product:
              type: object
              required:
                - id
                - name
                - department
                - category
                - photo_url
                - wholesale_price
                - retail_price
                - stock
                - discountable
              properties:
                id:
                  type: integer
                  format: int64
                name:
                  type: string
                description:
                  type: string
                department:
                  type: string
                  enum:
                    - mens
                    - womens
                    - kids
                category:
                  type: string
                photo_url:
                  type: string
                wholesale_price:
                  type: number
                  format: float
                retail_price:
                  type: number
                  format: float
                stock:
                  type: integer
                  format: int32
                discountable:
                  type: boolean
              xml:
                name: Product
            ApiResponse:
              type: object
              properties:
                Content-Type:
                  type: string
                Status-Code:
                  type: integer
                message:
                  type: string
                data:
                  type: array
                  items:
                    type: object

  MyApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref MyApiGateway
      StageName: prod

  MyApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt ProductLambda.Arn

  ProductLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt ProductLambdaRole.Arn # TODO
      Handler: index.handleHttpRequest
      Runtime: nodejs12.x
      Environment:
        Variables:
          Product_DB: !Sub "arn:aws:dynamodb:${AWS::Region}:*:table/${ProductTable}"
      Code:
        ZipFile: |
          exports.handlers = function(event, context) {}

  ProductLambdaRole: # -> AppAPIRole
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref BaseLambdaExecutionPolicy
      Policies:
        - PolicyName: readProducts
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:*:table/${ProductTable}"
        - PolicyName: readProductById
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:*:table/${ProductTable}"
         - PolicyName: updateProduct
           PolicyDocument:
             Version: "2012-10-17"
             Statement:
               - Effect: Allow
                 Action:
                   - dynamodb:UpdateItem
                 Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:*:table/${ProductTable}"
         - PolicyName: updateProduct
           PolicyDocument:
             Version: "2012-10-17"
             Statement:
               - Effect: Allow
                 Action:
                   - dynamodb:DeleteItem
                 Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:*:table/${ProductTable}"